
name: ScanForge

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run ScanForge (all scanners)
      run: |
        python main.py --all --excel ${{ github.workspace }}

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: scanforge-reports
        path: |
          combined.xlsx

    - name: Upload SBOM to Dependency-Track
      if: env.DT_API_KEY != ''
      run: |
        python -c "from scanners.dtrack_runner import DependencyTrackUploader as U; U().upload('combined.xml')"
